version: 2
updates:
  # Version updates for Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first"
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "hex"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first"
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "hex"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
